cloud:
  aws:
    region:
      static: ap-southeast-1
      auto: false
    credentials:
      access-key: <>
      secret-key: <>
    end-point:
      uri: https://sqs.ap-southeast-1.amazonaws.com/398378596368/rbn-queue